### ISSUE TITLE
Issue from 5.0 to 5.2

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azuread#192] opened 2021-09-19 01:16 UTC
I got this issue when upgraded to the 5.x versions

```
 panic: Unknown kind: bool
    goroutine 47 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/terraform.(*ResourceConfig).get(0xc0004eebd0, 0xc000678e40, 0x1f, 0xc0004eea50, 0x0, 0x1f, 0x7f5bde9125b8)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/terraform/resource.go:313 +0xa1f
    github.com/hashicorp/terraform-plugin-sdk/v2/terraform.(*ResourceConfig).IsComputed(0xc0004eebd0, 0xc000678e40, 0x1f, 0x1394640)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/terraform/resource.go:226 +0x4c
    github.com/hashicorp/terraform-plugin-sdk/v2/terraform.(*ResourceConfig).Get(0xc0004eebd0, 0xc000678e40, 0x1f, 0x15ce30c, 0xd, 0xc0004d3e98)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/terraform/resource.go:206 +0x4c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readPrimitive(0xc0004eec30, 0xc000678e40, 0x1f, 0xc000506f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1382cc0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/helper/schema/field_reader_config.go:223 +0x7c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0xc0004eec30, 0xc0004f15c0, 0x4, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/helper/schema/field_reader_config.go:101 +0x65c
```

**Comment by stack72** [comment] 2021-09-22 14:44
Hi @baoduy 

Sorry you are hitting this error - please can you tell me the resource this is happening on or a small snippet of code to recreate

Thanks 

Paul

**Comment by jkonecki-techfabric** [comment] 2021-09-28 06:57
Possible duplicate of #185

**Comment by stack72** [comment] 2021-09-30 18:53
You are correct here @jkonecki-techfabric - I will close this out as a dupe so we can track in the other issue

**Closed by stack72** 2021-09-30 18:53 UTC
Labels: resolution/duplicate, kind/bug, impact/panic, awaiting-feedback
