### ISSUE TITLE
Q: How do I register a single-page application?

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi-azuread#166] opened 2021-06-07 20:27 UTC
I'm trying to create a single-page application in azure ad, but I only find the `web` argument, https://github.com/pulumi/pulumi-azuread/blob/a00856045be80463c277d3cc4e0d6e9e2c312b51/sdk/nodejs/application.ts#L437. How do I create a single-page app in azure ad?

When created using the web property mentioned above I won't be marked as a SPA and I can't see the following message

![image](https://user-images.githubusercontent.com/501424/121083274-851f7d80-c7df-11eb-9fe2-cce0d44f2290.png)

that I do see on my manual registered apps.

Is there something I'm missing?

**Comment by infin8x** [comment] 2021-06-08 22:42
This appears to be an issue/feature request in the upstream Terraform provider (and from there, a feature request for the Azure APIs): https://github.com/hashicorp/terraform-provider-azuread/issues/286.

**Comment by leezen** [comment] 2021-06-09 00:22
Realized this is actually a duplicate of https://github.com/pulumi/pulumi-azuread/issues/92 so closing as such.

**Closed by leezen** 2021-06-09 00:22 UTC
Labels: awaiting-upstream, kind/enhancement, resolution/duplicate
